services:

  # postgres:
  #   image: postgres:17
  #   container_name: event-finder-postgres

  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: event_finder

  #   ports:
  #     - "5432:5432"

  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data


  rabbitmq:
    image: rabbitmq:4-management
    container_name: event-finder-rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  # redis:
  #   image: redis:8
  #   container_name: event-finder-redis

  #   ports:
  #     - "6379:6379"

  #   volumes:
  #     - redis_data:/data


volumes:
  # postgres_data:
  rabbitmq_data:
  # redis_data: